ASPNET_Project_Ten/Controllers/MusicController.cs
using ASPNET_Project_Eleven.Models;
using ASPNET_Project_Eleven.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.AspNetCore.DataProtection;
using ASPNET_Project_Eleven.Security;

namespace ASPNET_Project_Eleven.Controllers
{
    [Authorize(Policy = "ManagerLevelPolicy")]
    [Route("[controller]/[action]")]
    public class MusicController : Controller
    {
        private readonly IDatabaseRepository _databaseRepository;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly IDataProtector protector;

        public MusicController( IDatabaseRepository employeeRepository,
                                IWebHostEnvironment hostingEnvironment,
                                IDataProtectionProvider dataProtectionProvider,
                                DataProtectionPurposeStrings dataProtectionPurposeStrings)
        {
            _databaseRepository = employeeRepository;
            this.hostingEnvironment = hostingEnvironment;
            protector = dataProtectionProvider.CreateProtector(dataProtectionPurposeStrings.PlaylistIdRouteValue);
        }

        // GET: /<controller>/
        [AllowAnonymous]
        [ActionName("ListPlaylists")]
        public IActionResult ListPlaylists()
        {
            IEnumerable<Playlist> model = _databaseRepository.GetAllPlaylists().Select(playlist => {
                playlist.EncryptedId = protector.Protect(playlist.Id.ToString());
                playlist.Id = 0;
                return playlist;
            });
            return View(model);
        }

        [AllowAnonymous]
        [ActionName("ListEditPlaylists")]
        public IActionResult ListEditPlaylists()
        {
            IEnumerable<Playlist> model = _databaseRepository.GetAllPlaylists().Select(playlist => {
                playlist.EncryptedId = protector.Protect(playlist.Id.ToString());
                playlist.Id = 0;
                return playlist;
            });
            return View(model);
        }

        [Route("{id}")]
        [AllowAnonymous]
        [ActionName("DetailsPlaylist")]
        public ViewResult DetailsPlaylist(string id)
        {
            int playlistId = Convert.ToInt32(protector.Unprotect(id));
            Playlist playlist = _databaseRepository.GetPlaylist(playlistId);

            // we hide the Id and set it to 0 in a new instance of playlist
            playlist.Id = 0;
            if (playlist == null)
            {
                Response.StatusCode = 404;
                return View("EmployeeNotFound", playlistId);
            }

            PlaylistDetailsViewModel articleDetailsViewModel = new PlaylistDetailsViewModel()
            {
                Playlist = playlist
            };
            return View(articleDetailsViewModel);
        }

        [HttpGet]
        [ActionName(nameof(CreatePlaylist))]
        public ViewResult CreatePlaylist()
        {
            var playlists = _databaseRepository.GetAllPlaylists();

            double maxNumber;
            if (playlists.Any())
            {
                maxNumber = (from Playlist p in playlists
                             select p.Rank).Max();
            }
            else
            {
                maxNumber = 0;
            }
            ViewBag.MaxRank = maxNumber;
            return View();
        }

        [HttpPost]
        [ActionName(nameof(CreatePlaylist))]
        public IActionResult CreatePlaylist(PlaylistCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadedFile(model);
                Playlist playlist = new Playlist
                {
                    Title = model.Title,
                    PlaylistBody = model.PlaylistBody,
                    PhotoPath = uniqueFileName,
                    Rank = model.Rank
                };
                _databaseRepository.AddPlaylist(playlist);
                return RedirectToAction("DetailsPlaylist", new { id = protector.Protect(playlist.Id.ToString()) });
            }

            return View();
        }

        [HttpGet]
        [ActionName("EditPlaylist")]
        public ViewResult EditPlaylist(string id)
        {
            int playlistId = Convert.ToInt32(protector.Unprotect(id));
            Playlist playlist = _databaseRepository.GetPlaylist(playlistId);
            PlaylistEditViewModel employeeEditViewModel = new PlaylistEditViewModel()
            {
                EncryptedId = id,
                Title = playlist.Title,
                PlaylistBody = playlist.PlaylistBody,
                ExistingPhotoPath = playlist.PhotoPath,
                Rank = playlist.Rank
            };
            return View(employeeEditViewModel);
        }

        [HttpPost]
        [ActionName("EditPlaylist")]
        public IActionResult EditPlaylist(PlaylistEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Playlist playlist = _databaseRepository.GetPlaylist(Convert.ToInt32(protector.Unprotect(model.EncryptedId)));
                playlist.Title = model.Title;
                playlist.PlaylistBody = model.PlaylistBody;
                playlist.Rank = model.Rank;

                if (model.Photo != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath,
                            "images", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    playlist.PhotoPath = ProcessUploadedFile(model);
                }

                Playlist updatedPlaylist = _databaseRepository.UpdatePlaylist(playlist);

                return RedirectToAction("ListEditPlaylists");
            }

            return View(model);
        }

        [HttpPost]
        [ActionName("DeletePlaylist")]
        [Authorize(Policy = "AdminLevelPolicy")]
        public IActionResult DeletePlaylist(string id)
        {
            if(id.Equals(null))
            {
                throw new Exception();
            }
            int playlistId = Convert.ToInt32(protector.Unprotect(id));
            _databaseRepository.DeletePlaylist(playlistId);
            return RedirectToAction("ListPlaylists");
        }

        private string ProcessUploadedFile(PlaylistCreateViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }


    }
}

ASPNET_Project_Ten/Views/Music/CreatePlaylist.cshtml
@model PlaylistCreateViewModel
@inject IDatabaseRepository _databaseRepository
@{
    ViewBag.Title = "Create Article";
}

<div>
    <p>Current top rank is @ViewBag.MaxRank</p>
</div>

<form enctype="multipart/form-data" asp-controller="Music" asp-action="CreatePlaylist" method="post" class="mt-3">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row customSmallPadding">
        <label asp-for="Title" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Title" class="form-control" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row customSmallPadding">
        <label asp-for="PlaylistBody" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <textarea asp-for="PlaylistBody" class="form-control" placeholder="ArticleBody" rows="7"></textarea>
            <span asp-validation-for="PlaylistBody" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row customSmallPadding">
        <label asp-for="Rank" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Rank" class="form-control" placeholder="Rank, double" />
            <span asp-validation-for="Rank" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row customSmallPadding">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input multiple asp-for="Photo" class="form-control custom-file-input" type="file" placeholder="Choose File..." />
            </div>
        </div>
    </div>

    <div>
        <button type="submit" class="btn btn-primary m-1">Create</button>
    </div>

    @section Scripts{

        <script>$(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var filename = $(this).val().split("\\").pop;
                    $(this).next('.custom-file-label').html(fileName);
                });
            })</script>
    }
</form>

ASPNET_Project_Ten/Views/Music/DetailsPlaylist.cshtml
@model PlaylistDetailsViewModel
@{
    ViewBag.Title = Model.Playlist.Title;
}

<br />
<h4>@Model.Playlist.Title</h4>
<br />
<p style="white-space: pre-wrap;">@Model.Playlist.PlaylistBody</p>
<br />

ASPNET_Project_Ten/Views/Music/EditPlaylist.cshtml
@model PlaylistEditViewModel
@inject IDatabaseRepository _databaseRepository
@{
    ViewBag.Title = "Edit Playlist";
}

<div>
    <p>@ViewBag.MaxRank</p>
</div>

<form enctype="multipart/form-data" asp-controller="Music" asp-action="EditPlaylist" method="post" class="mt-3">

    <input hidden asp-for="EncryptedId" />
    <input hidden asp-for="ExistingPhotoPath" />

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row customSmallPadding">
        <label asp-for="Title" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Title" class="form-control" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row customSmallPadding">
        <label asp-for="PlaylistBody" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <textarea asp-for="PlaylistBody" class="form-control" placeholder="ArticleBody" rows="7"></textarea>
            <span asp-validation-for="PlaylistBody" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row customSmallPadding">
        <label asp-for="Rank" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Rank" class="form-control" placeholder="Rank, double" />
            <span asp-validation-for="Rank" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row customSmallPadding">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input multiple asp-for="Photo" class="form-control custom-file-input" type="file" placeholder="Choose File..." />
            </div>
        </div>
    </div>

    <div class="form-group row m-1">
        <div class="col-sm-10 d-flex justify-content-start" style="padding:0px">
            <button type="submit" class="btn btn-primary m-1 customNoMarginLeft">Edit</button>
            <a asp-controller="Music" asp-action="ListEditPlaylists"
               class="btn btn-primary m-1">Cancel</a>
            <button type="button" class="btn btn-outline-danger m-1" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Almost Delete
            </button>
        </div>
    </div>


    @section Scripts{

        <script>$(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var filename = $(this).val().split("\\").pop;
                    $(this).next('.custom-file-label').html(fileName);
                });
            })</script>
    }
</form>

<!-- Modal -->
<!-- this needs to be at the bottom of the html -->
<div class="modal fade" data-bs-keyboard="false" data-bs-backdrop="static" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Making sure...</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this article?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

                <form enctype="multipart/form-data" asp-controller="Music" asp-action="DeletePlaylist"
                      asp-route-id="@Model.EncryptedId" method="post">
                    <div>
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

ASPNET_Project_Ten/Views/Music/ListEditPlaylists.cshtml
@model IEnumerable<Playlist>

@{
    var ordered = Model.OrderByDescending(p => p.Rank);
}

<h5>List of Articles Under Development</h5>
<div class="container">
    <div class="d-grid justify-content-between">
        <div class="card-group">
            @foreach (var playlist in ordered)
            {
                var photoPath = "~/images/" + (playlist.PhotoPath ?? "noimage.jpg");
                <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
                    <div class="card-header">
                        <h3>@playlist.Title</h3>
                    </div>
                    <div class="card-body d-flex flex-column justify-content-between">
                        <img class="card-img-top imageThumbnail" src=@photoPath asp-append-version="true" />
                        <div class="card-footer text-center align-baseline">
                            <a asp-controller="Music" asp-action="DetailsPlaylist" asp-route-id="@playlist.EncryptedId"
                               class="btn btn-outline-primary m-1">View</a>
                            <a asp-controller="Music" asp-action="EditPlaylist" asp-route-id="@playlist.EncryptedId"
                               class="btn btn-outline-primary m-1">Edit</a>
                            <!--<a href="#"
                                class="btn btn-danger m-1">Delete</a>-->
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

ASPNET_Project_Ten/Views/Music/ListPlaylists.cshtml
@using System.ComponentModel.DataAnnotations;
@model IEnumerable<Playlist>

@{
    var ordered = Model.OrderByDescending(x => x.Rank);
}

<div class="container">
    
    <div class="row">
        @foreach (var playlist in ordered)
        {
            <!--
                string photoPath = "";
                if (playlist.PhotoPath != null)
                {
                    photoPath = "~/images/" + (playlist.PhotoPath ?? "noimage.jpg");
                    <style type="text/css">
                            .bgimg {
                                background-image: url('Url.Content(photoPath)');
                            }
                    </style>
                }
            -->
            // <img class="imageThumbnail" src=@photoPath asp-append-version="true" />
            string photoPath = "~/images/" + (playlist.PhotoPath ?? "");
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12" style="padding:10px">
                <div class="card border-0" style="        height: 200px;
                                    background: url('@Url.Content(photoPath)');
                                    background-repeat: no-repeat;
                                    -webkit-background-size: cover;
                                    -moz-background-size: cover;
                                    -o-background-size: cover;
                                    background-size: cover;
                                    background-position: center;"
                            >
                    <!--  -->
                    <div class="card-body">
                        <br />
                        <a class="card-title d-flex justify-content-center text-center"
                           asp-controller="Music" asp-action="DetailsPlaylist" asp-route-id="@playlist.EncryptedId">
                            <h4 class="outlinedText">@playlist.Title</h4>
                        </a>
                        <!--
                        <p class="text-secondary d-flex justify-content-center" style="margin-bottom:0.5rem !important">---</p>
                        <hr class="d-flex justify-content-center outlinedText" style="width:20%;"/>
                        <p class="text-secondary d-flex justify-content-center" style="margin-bottom:0.5rem !important"></p>
                    -->
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ASPNET_Project_Ten/Views/Music/PracticePage.cshtml
<div class="container">
    <p>
        Alt / Punk // Rock

        Sugarcult - Los Angeles: https://www.youtube.com/watch?v=vATvNdMS-QM
        Fall Out Boy - I Don't Care: https://www.youtube.com/watch?v=Alh6iIvVN9o
        Good Charlotte - The Anthem: https://www.youtube.com/watch?v=desJKYvdq9A
        Yellowcard - Way Away: https://www.youtube.com/watch?v=k4t5qqdP7As
        Red Hot Chili Peppers - By The Way: https://www.youtube.com/watch?v=JnfyjwChuNU
        Sugarcult - She's The Blade: https://www.youtube.com/watch?v=J5EA82jKq4s
        Hollywood Undead - Young: https://www.youtube.com/watch?v=R_HHm9ki3JI
        Sugarcult - Memory: https://www.youtube.com/watch?v=iEmBFk6P2Ww
        Blink 182 - First Date: https://www.youtube.com/watch?v=vVy9Lgpg1m8
        Mando Diao - Sheepdog: https://www.youtube.com/watch?v=bFE1QEQJ6oY
        Bloc Party - Helicopter: https://www.youtube.com/watch?v=2R6S5CJWlco
        Fall Out Boy - Thnks fr th Mmrs: https://www.youtube.com/watch?v=SafZ0r2zXyk
        My Chemical Romance - The Sharpest Lives: https://www.youtube.com/watch?v=7be0fq_1Hwc
        My Chemical Romance - Famous Last Words: https://www.youtube.com/watch?v=ex-ICeh8y9g
        My Chemical Romance - This Is How I Disappear: https://www.youtube.com/watch?v=paFCInMIPfA
        My Chemical Romance - You Know What They Do to Guys Like Us in Prison: https://www.youtube.com/watch?v=ShQdOf2zAzc
        My Chemical Romance - It's Not a Fashion Statement, It's a Deathwish: https://www.youtube.com/watch?v=uPMDRsH1YRU
        Green Day - Holiday: https://www.youtube.com/watch?v=A1OqtIqzScI
        AFI - Prelude 12/21 + Miss Murder: https://www.youtube.com/watch?v=YU4hhNKsPog
        The Cab - Can You Keep a Secret?: https://www.youtube.com/watch?v=mBYY4Ifr7b0
        Sum 41 - Still Waiting: https://www.youtube.com/watch?v=qO-mSLxih-c
        Good Charlotte feat M. Shadows, Synyster Gates - The River: https://www.youtube.com/watch?v=yVm8PjWCvLg
        The All-American Rejects - Dirty Little Secret: https://www.youtube.com/watch?v=gPDcwjJ8pLg
        Panic! At The Disco - I Write Sins Not Tragedies: https://www.youtube.com/watch?v=-3GBJZzPkYQ
        Paramore - Misery Business: https://www.youtube.com/watch?v=1VPotzhpAGE
        Fall Out Boy - This Ain't A Scene, It's An Arms Race: https://www.youtube.com/watch?v=KGSBtTfe0V0
        Cute Is What We Aim For - Hollywood: https://www.youtube.com/watch?v=wzyOx2YVVdA
        Bowling For Soup - 1985: https://www.youtube.com/watch?v=K38xNqZvBJI
        Ween - You Fucked Up: https://www.youtube.com/watch?v=6Se9vvLsVUI
        Maroon 5 - Misery: https://www.youtube.com/watch?v=6g6g2mvItp4
        The Killers - Midnight Show: https://www.youtube.com/watch?v=LYsTFZnj4jw
        Linkin Park - What I`ve Done: https://www.youtube.com/watch?v=dpif2shN0vg
        5 Seconds of Summer - Don't Stop: https://www.youtube.com/watch?v=MKfzMOC19Fc
        Maroon 5 - This Love: https://www.youtube.com/watch?v=AqQuRw0S6b4
        All Time Low - Umbrella: https://www.youtube.com/watch?v=dVEZzUpRPZo
        Royal Blood - Trouble's Coming: https://www.youtube.com/watch?v=nuYSarZXzrE
        Arctic Monkeys - Teddy Picker: https://www.youtube.com/watch?v=VredAgNScOw
        Panic! At The Disco - Lying Is the Most Fun a Girl Can Have Without Taking Her Clothes Off: https://www.youtube.com/watch?v=U-1A0jfF67Q


    </p>
</div>